application:
  debug: True
  environment: 'dev'
  logfile: '/var/logs/byoda/byoda.log'
  root_dir: '/byoda'
  network: 'byoda.net'

dirserver:
  name: 'directoryserver'
  dnsdb: "postgresql://<username>:<password?@<ip>/<database>"
  roles:
    - directory
  private_key_password: 'byoda'

svcserver:
  name: 'serviceserver'
  roles:
    - service
  service: default
  private_key_password: 'byoda'

podserver:
  account: 'test'
  roles:
    - pod
  private_key_password: 'byoda'